name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  testing:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]

    name: PHP (${{ matrix.os }})

    steps:

      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'

      - name: Setup Problem Matches
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install Node Dependencies
        run: npm ci

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --no-progress --ansi

      - name: Setup Laravel
        run: |
          php -r "file_exists('.env') || copy('.env.example', '.env');"
          php artisan key:generate

      - name: Build Assets
        run: npm run build

      - name: Run Pest Tests
        run: vendor/bin/pest -p --colors=always
